const strings = {
  vi: {
    title: 'Audio Sample Generator',
    desc: 'Tạo và tải xuống test tone hoặc noise.',
    mode_label: 'Chế độ',
    mode_tooltip: 'Chọn chế độ âm thanh',
    waveform_label: 'Dạng sóng',
    waveform_tooltip: 'Chọn dạng sóng âm thanh',
    freq_label: 'Tần số (Hz)',
    freq_tooltip: 'Độ cao/thấp của âm thanh',
    amp_label: 'Biên độ (0.0 - 1.0)',
    amp_tooltip: 'Âm lượng của tín hiệu',
    dur_label: 'Độ dài (giây)',
    dur_tooltip: 'Thời gian phát',
    sr_label: 'Tần số mẫu (Hz)',
    sr_tooltip: 'Số lần ghi âm mỗi giây',
    channels_label: 'Kênh',
    channels_tooltip: 'Mono hoặc Stereo',
    bitdepth_label: 'Bit Depth',
    bitdepth_tooltip: 'VI: Độ sâu bit - số bit dùng để lưu mỗi mẫu âm thanh. 16-bit: CD quality, đủ cho hầu hết mục đích (96 dB dynamic range). 24-bit: Professional recording, studio (144 dB). 32-bit: Mastering, xử lý chuyên sâu (192 dB). Cao hơn = file lớn hơn, ít noise hơn, nhưng tai người khó phân biệt trên 16-bit.',
    norm_label: 'Chuẩn hoá?',
    norm_tooltip: 'Tăng biên độ tối đa',
    play: 'Phát',
    play_tooltip: 'Phát âm thanh',
    stop: 'Dừng',
    stop_tooltip: 'Dừng phát',
    download: 'Render & Tải xuống WAV',
    download_tooltip: 'Tạo file WAV',
    preset_title: 'Preset Tần Số',
    bass_label: 'Dải Bass',
    mid_label: 'Dải Mid',
    treble_label: 'Dải Treble',
    special_label: 'Test Đặc Biệt',
    preset20_tooltip: '20Hz - Infrasound, test sub cực mạnh',
    preset35_tooltip: '35Hz - Bass cực sâu, test subwoofer',
    preset40_tooltip: '40Hz - Sub-bass, rạp chiếu phim',
    preset60_tooltip: '60Hz - Bass thấp, EDM, hip-hop',
    preset80_tooltip: '80Hz - Bass punch, kick drum',
    preset100_tooltip: '100Hz - Bass trung, bass guitar',
    preset125_tooltip: '125Hz - Bass warm, acoustic',
    preset250_tooltip: '250Hz - Low-mid, giọng nam',
    preset315_tooltip: '315Hz - Body, độ dày vocal',
    preset500_tooltip: '500Hz - Mid, vocal clarity',
    preset630_tooltip: '630Hz - Vocal fundamental',
    preset1000_tooltip: '1kHz - Reference tone chuẩn',
    preset1250_tooltip: '1.25kHz - Articulation, độ rõ lời',
    preset2000_tooltip: '2kHz - High-mid, tai nhạy nhất',
    preset2500_tooltip: '2.5kHz - Presence peak',
    preset4000_tooltip: '4kHz - Treble thấp, consonant',
    preset5000_tooltip: '5kHz - Sibilance, tiếng s',
    preset8000_tooltip: '8kHz - Treble cao, brilliance',
    preset10000_tooltip: '10kHz - Air, sparkle',
    preset12500_tooltip: '12.5kHz - Upper air, shimmer',
    preset16000_tooltip: '16kHz - Giới hạn trên tai người',
    preset_pinknoise_tooltip: 'Pink Noise - Test cân bằng tần số',
    preset_whitenoise_tooltip: 'White Noise - Burn-in loa',
    footer: 'Lưu ý: trình duyệt có thể giới hạn âm lượng.',
    langlabel: 'Ngôn ngữ'
  },
  en: {
    title: 'Audio Sample Generator',
    desc: 'Generate and download test tones or noise.',
    mode_label: 'Mode',
    mode_tooltip: 'Mode for audio',
    waveform_label: 'Waveform',
    waveform_tooltip: 'Select audio waveform',
    freq_label: 'Frequency (Hz)',
    freq_tooltip: 'Pitch/tone height',
    amp_label: 'Amplitude (0.0 - 1.0)',
    amp_tooltip: 'Signal volume',
    dur_label: 'Duration (seconds)',
    dur_tooltip: 'Playback time',
    sr_label: 'Sample rate (Hz)',
    sr_tooltip: 'Samples per second',
    channels_label: 'Channel',
    channels_tooltip: 'Mono or Stereo',
    bitdepth_label: 'Bit Depth',
    bitdepth_tooltip: 'EN: Bit depth - number of bits used to store each audio sample. 16-bit: CD quality, sufficient for most purposes (96 dB dynamic range). 24-bit: Professional recording, studio (144 dB). 32-bit: Mastering, deep processing (192 dB). Higher = larger file, less noise, but humans struggle to distinguish above 16-bit.',
    norm_label: 'Normalize?',
    norm_tooltip: 'Boost to max amplitude',
    play: 'Play',
    play_tooltip: 'Play audio',
    stop: 'Stop',
    stop_tooltip: 'Stop playback',
    download: 'Render & Download WAV',
    download_tooltip: 'Generate WAV file',
    preset_title: 'Frequency Presets',
    bass_label: 'Bass Range',
    mid_label: 'Midrange',
    treble_label: 'Treble & Air',
    special_label: 'Special Tests',
    preset20_tooltip: '20Hz - Infrasound, extreme sub test',
    preset35_tooltip: '35Hz - Deep bass, subwoofer test',
    preset40_tooltip: '40Hz - Sub-bass, cinema',
    preset60_tooltip: '60Hz - Low bass, EDM, hip-hop',
    preset80_tooltip: '80Hz - Bass punch, kick drum',
    preset100_tooltip: '100Hz - Mid-bass, bass guitar',
    preset125_tooltip: '125Hz - Bass warmth, acoustic',
    preset250_tooltip: '250Hz - Low-mid, male vocals',
    preset315_tooltip: '315Hz - Body, vocal thickness',
    preset500_tooltip: '500Hz - Mid, vocal clarity',
    preset630_tooltip: '630Hz - Vocal fundamental',
    preset1000_tooltip: '1kHz - Reference tone standard',
    preset1250_tooltip: '1.25kHz - Articulation, clarity',
    preset2000_tooltip: '2kHz - High-mid, most sensitive',
    preset2500_tooltip: '2.5kHz - Presence peak',
    preset4000_tooltip: '4kHz - Lower treble, consonants',
    preset5000_tooltip: '5kHz - Sibilance, s sounds',
    preset8000_tooltip: '8kHz - Upper treble, brilliance',
    preset10000_tooltip: '10kHz - Air, sparkle',
    preset12500_tooltip: '12.5kHz - Upper air, shimmer',
    preset16000_tooltip: '16kHz - Upper hearing limit',
    preset_pinknoise_tooltip: 'Pink Noise - Frequency balance test',
    preset_whitenoise_tooltip: 'White Noise - Speaker burn-in',
    footer: 'Note: browsers may limit output volume.',
    langlabel: 'Language'
  }
};